#!/bin/bash

TEMP_FILE=$TGLOCKSYS/logs/access/read.tmp

if [[ $(grep -o "ok" $TEMP_FILE) == "ok" ]];
then
#echo "Card Read Successfully"
#python $TGLOCKSYS/misc/scripts/buzzer.py cardRead_success
checkAuth
else
echo "Card Unrecognized"
python $TGLOCKSYS/misc/scripts/buzzer.py cardRead_fail &
python $TGLOCKSYS/misc/scripts/readerLED.py RLED_blink 2 &
#nop 
# do nothing
fi
