#!/bin/bash

TEMP_FILE=/home/ecel2b40/Documents/TGLockSystem/logs/access/read.tmp

if [[ $(grep -o "ok" $TEMP_FILE) == "ok" ]];
then
#echo "Card Read Successfully"
#python /home/ecel2b40/Documents/TGLockSystem/misc/scripts/buzzer.py cardRead_success
/home/ecel2b40/Documents/TGLockSystem/checkAuth
else
echo "Card Unrecognized"
#python /home/ecel2b40/Documents/TGLockSystem/misc/scripts/buzzer.py cardRead_fail &
python /home/ecel2b40/Documents/TGLockSystem/misc/scripts/readerLED.py RLED_blink 2 &
#nop 
# do nothing
fi
