#!/bin/bash
PORT="/dev/ttyACM0"
TEMP_FILE=/home/ecel2b40/Documents/TGLockSystem/logs/access/read.tmp
RAW=''

function readCard(){
 proxmark3 -p $PORT -c "lf io read" |grep "IO" | sed "s/+/$(date '+%Y%b%d_%H%M%S'|tr '[:lower:]' '[:upper:]')/"> /home/ecel2b40/Documents/TGLockSystem/logs/access/read.tmp
}

function getCardRaw(){
 RAW=$(grep -oP '(?<=Raw: ).{16}' "$TEMP_FILE")
 echo $RAW
}

function readCardRaw(){
 python3 "/home/ecel2b40/Documents/TGLockSystem/misc/scripts/readerLED.py" BLED_on 1 &
 readCard
 getCardRaw
 if [[ -z "$RAW" || "$RAW" == +([[:space:]]) ]];then
     # Fail feedback signals
     python3 "/home/ecel2b40/Documents/TGLockSystem/misc/scripts/buzzer.py" cardRead_fail &
     python3 "/home/ecel2b40/Documents/TGLockSystem/misc/scripts/readerLED.py" RLED_blink 4 &
 else
     # Success feedback signals
     python3 "/home/ecel2b40/Documents/TGLockSystem/misc/scripts/buzzer.py" cardRegister &
     python3 "/home/ecel2b40/Documents/TGLockSystem/misc/scripts/readerLED.py" BLED_blink 4 &
 fi
 echo $RAW
}

function card_register() {
    local HID=$HID
    local HNAME=$HNAME

    # Check if arguments are provided
    if [[ -z "$HID" || -z "$HNAME" ]]; then
        echo "Usage: readIDcard <HID> <HNAME>"
        return 1
    fi

    echo -e "Place your card on the reader and press Enter... \c"
    read -r tmpIGNORE
    echo "Reading ID Card..."
    
    # Execute the read command
    readCard

    # Check for success in the log file
    if grep -q 'ok' "/home/ecel2b40/Documents/TGLockSystem/logs/access/read.tmp"; then
        # Process card data
        record=$(sed "s/-/,/g" "/home/ecel2b40/Documents/TGLockSystem/logs/access/read.tmp" | tr -d ' ')
        getCardRaw
        raw=$RAW

        # Update data files
        echo "${HID},${raw}" >> "/home/ecel2b40/Documents/TGLockSystem/data/access_list.csv"
        echo "${HID}" >> "/home/ecel2b40/Documents/TGLockSystem/data/granted.csv"
        
        # Log the transaction
        record+=",${HID},${HNAME}"
        echo "$record" >> "/home/ecel2b40/Documents/TGLockSystem/data/.bkp.log"

        echo "New card has been added. Access has been granted."

        # Success feedback signals
        python3 "/home/ecel2b40/Documents/TGLockSystem/misc/scripts/buzzer.py" cardRegister &
        python3 "/home/ecel2b40/Documents/TGLockSystem/misc/scripts/readerLED.py" BLED_blink 4 &
    else
        echo "Cannot read your card. Try again."
        python3 "/home/ecel2b40/Documents/TGLockSystem/misc/scripts/buzzer.py" cardRead_fail &
        return 1
    fi
}

function auto_card_register() {
    local HID=$HID
    local HNAME=$HNAME

    # Check if arguments are provided
    if [[ -z "$HID" || -z "$HNAME" ]]; then
        echo "Usage: readIDcard <HID> <HNAME>"
        return 1
    fi

    #echo -e "Place your card on the reader and press Enter... \c"
    #read -r tmpIGNORE
    echo "Reading ID Card..."
    
    # Execute the read command
    readCard
    getCardRaw
    raw=$RAW

    # Check for success in the log file
    if grep -q 'ok' "/home/ecel2b40/Documents/TGLockSystem/logs/access/read.tmp"; then
        # Process card data
        record=$(sed "s/-/,/g" "/home/ecel2b40/Documents/TGLockSystem/logs/access/read.tmp" | tr -d ' ')
        getCardRaw
        raw=$RAW

        # Update data files
        echo "${HID},${raw}" >> "/home/ecel2b40/Documents/TGLockSystem/data/access_list.csv"
        echo "${HID}" >> "/home/ecel2b40/Documents/TGLockSystem/data/granted.csv"
        
        # Log the transaction
        record+=",${HID},${HNAME}"
        echo "$record" >> "/home/ecel2b40/Documents/TGLockSystem/data/.bkp.log"

        echo "New card has been added. Access has been granted."

        # Success feedback signals
        python3 "/home/ecel2b40/Documents/TGLockSystem/misc/scripts/buzzer.py" cardRegister &
        python3 "/home/ecel2b40/Documents/TGLockSystem/misc/scripts/readerLED.py" BLED_blink 4 &
    else
        echo " "
        echo "Cannot read your card. Try again."
        # Fail feedback signals
        python3 "/home/ecel2b40/Documents/TGLockSystem/misc/scripts/buzzer.py" cardRead_fail &
        python3 "/home/ecel2b40/Documents/TGLockSystem/misc/scripts/readerLED.py" RLED_blink 2 &
        return 1
    fi
}

if [ $# -lt 1 ];then
 # read card from reader
 readCard
 #python /home/ecel2b40/Documents/TGLockSystem/misc/scripts/readerLED.py BLED_blink 1
 
 # check that the card read is correct 
 /home/ecel2b40/Documents/TGLockSystem/confirmIDcard
 
else if [ $# -gt 0 ] && [ $# -lt 4 ];then
 if [ $# -eq 1 ];then
  if [ $1 == "-h" ] || [ $1 == "--help" ];then
   echo -e "Usage: readIDcard [OPTION]... [ARGUMENTS]...\nRead ID cards and register new cards to the system\nOPTION:\n   -h   --help\tshow command help.\n   register\tadd new card to the system.\nARGUMENTS:\n\tHolder_ID\tIdentification number of the card holder.\n\tHolder_Name\tFull name of the card holder."
  fi
  if [ $1 == "register" ];then
   python /home/ecel2b40/Documents/TGLockSystem/misc/scripts/readerLED.py BLED_ON &
   python /home/ecel2b40/Documents/TGLockSystem/misc/scripts/buzzer.py cardRead_success &
   echo -e "Enter Card Holder ID: \c"
   read HID
   echo -e "Enter Card Holder Full Name: \c"
   read HNAME
   card_register # Call function to register ID card
  fi
  if [ $1 == "readCardRaw" ];then
   readCardRaw
  fi 
 fi
 if [ $# -eq 2 ];then
  #echo "two: $@"
  HID="$1"
  HNAME="$2"
  card_register # Call function to register ID card
 fi
 if [ $# -eq 3 ];then
  #echo "three: $@"
  if [ $3 == "register" ];then
   HID="$1"
   HNAME="$2"
   auto_card_register # Call function to register ID card automatically
  fi
 fi
fi
fi 
